server:
  port: 31001
spring:
  application:
    name: nm-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017/m_cms
  rabbitmq:
    host: 127.0.0.1c
    port: 5672
    username: guest
    password: guest
    virtualHost: /